apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: bohdankostenko/testk8:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: static-volume
              mountPath: /app/static
      volumes:
        - name: static-volume
          emptyDir: {}
